### ISSUE TITLE
deno 2.1 breaks the patch

### ISSUE THREAD

**Issue by Amatewasu** [chrisabrams/deno-with-prisma#1]
Hi!

Thank you for publishing this workaround. I was using it to use prisma with deno but it looks like the version 2.1 of deno breaks it.

Indeed, I have the following error with deno 2.1.0:
```bash
$ deno upgrade --version 2.1.0
Current Deno version: v2.0.6
Downloading https://github.com/denoland/deno/releases/download/v2.1.0/deno-x86_64-unknown-linux-gnu.zip
Deno is upgrading to version 2.1.0

Upgraded successfully to Deno v2.1.0 (stable)

Release notes:

  https://github.com/denoland/deno/releases/tag/v2.1.0

Blog post:

  https://deno.com/blog/v2.1

$ deno task dev:server
Task dev:server deno run --watch -A server/index.ts
Watcher Process started.
Auth0 Management Client initialized with token.
error: Uncaught (in promise) ReferenceError: exports is not defined
Object.defineProperty(exports, "__esModule", { value: true });
                      ^
    at file:///path/to/your/project/prisma/generated/client/index.js:2:23
    at loadESMFromCJS (node:module:761:21)
    at Module._compile (node:module:722:12)
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:754:10)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:797:16)
    at file:///path/to/your/project/prisma/client.ts:5:16

    info: Deno supports CommonJS modules in .cjs files, or when the closest
          package.json has a "type": "commonjs" option.
    hint: Rewrite this module to ESM,
          or change the file extension to .cjs,
          or add package.json next to the file with "type": "commonjs" option.
    docs: https://docs.deno.com/go/commonjs
Watcher Process failed. Restarting on file change...
```

But it works nicely with deno 2.0.6:
```bash
user@HOSTNAME:~/dashboard(main)$ deno upgrade --version 2.0.6
Current Deno version: v2.0.5
Downloading https://github.com/denoland/deno/releases/download/v2.0.6/deno-x86_64-unknown-linux-gnu.zip
Deno is upgrading to version 2.0.6

Upgraded successfully to Deno v2.0.6 (stable)

user@HOSTNAME:~/dashboard(main)$ deno task dev:server
Task dev:server deno run --watch -A server/index.ts
Watcher Process started.
Listening on http://0.0.0.0:8000/
^C
```

It is likely to be linked with the [CommonJS change of Deno 2.1](https://deno.com/blog/v2.1#better-commonjs-support). I have tried to create a `package.json` file in the generated folder but I did not achieve to make it work.

Do you have any idea to make it works folks?

Have a great day!

**Comment by chrisabrams** [comment]
Yes this is from Deno’s update on how they manage commonjs files now in
2.1, which requires the module to be explicitly commonjs — it’s essentially
the opposite of Node which requires ESM to be explicit. I can provide a
patch for this tomorrow, I’ll ping you on the PR.

Chris Abrams

**Comment by chrisabrams** [comment]
@Amatewasu I just merged the fix!

**Comment by Amatewasu** [comment]
Thanks a lot!!

**Comment by Amatewasu** [comment]
(I just tested and it works like a charm, thanks a lot!)
